### ISSUE TITLE
Generation of MELs

### ISSUE THREAD

**Issue by egorsmkv** [WelkinYang/WaveODE#2]
I am using [own dataset](https://huggingface.co/datasets/Yehor/ukrainian-tts-lada) in my testing. During training, the train.py requires NPY files with MELs of WAVs. 

Can you, please, look on my script that extracts them https://github.com/egorsmkv/WaveODE/blob/main/generate_mels.py ?

Because the repository already has pre-computed MELs and I would like to share the code with colleagues in order they could also run it with own datasets.

**Comment by WelkinYang** [comment]
The "testdata" is just test data so that you can run the project without any modifications. For your own dataset, you can use your own “generate_mels” script to extract the mels and wavs and place them in your directory, then modify the "feature_dirs" in config.yaml to your own directory . You can check the readme for a detailed explanation.

**Comment by egorsmkv** [comment]
Thank you, @WelkinYang !
